### PR TITLE
Caching done, pushing back to master

### PR DESCRIPTION
**Pull request by sckott**

### CODE REVIEW

**Comment by cboettig** [comment]
Nice! So does this restrict us to certain query fields? The code still looks pretty general.

**Comment by sckott** [comment]
@cboettig no, didn't change possible query fields

**Comment by cboettig** [comment]
awesome.  I think we will be able to restrict them in general (probably to
species, genus, and speccode in most cases), since the most typical
workflow is to have a list of species / taxaonomic groups a user wants to
query.  It doesn't address the issue of a user who wants to know which fish
have a certain property (e.g. are "threatened" or "elctrogenic") though.

Of course a user could always query on an empty species name to get the
whole table and then subset, but that's a high-bandwidth approach.  It
might make sense for certain analyses all the same.

**Comment by sckott** [comment]
@cboettig moving to the issue #8

**Pull request merged**
